// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Thu Apr 30 15:49:49 2015

sign_gen sign_gen_inst
(
	.clk_dac(clk_dac_sig) ,	// input  clk_dac_sig
	.value(value_sig) ,	// output [13:0] value_sig
	.enable(enable_sig) ,	// input  enable_sig
	.reset(reset_sig) ,	// input  reset_sig
	.finished(finished_sig) ,	// output  finished_sig
	.switch(switch_sig) ,	// input [3:0] switch_sig
	.re_switch(re_switch_sig) 	// output [3:0] re_switch_sig
);

